### ISSUE TITLE
Serve Images from CDN instead of locally

### ISSUE THREAD

**Issue by orama254** [reactdeveloperske/reactdevske-website#118]
### Description

Currently the images are being served locally which hinders on the performance of the website.

A proposed solution would be to serve the images from a CDN

### Additional information

Here are the links to add from the CDN:

https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532589/website-images/physical_meetup_fqkitv.jpg

https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532589/website-images/weekly_standups_lg3rth.jpg @isaack-mungui 

https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532589/website-images/community_sessions_xsyd8d.jpg @remigathoni

https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532588/website-images/hero-image_dqpm0k.jpg @gitahievans

https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532588/website-images/no-image_nnaxwk.jpg @EstherWMaina 

https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532588/website-images/mentorship-image_tz0mor.jpg

https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532588/website-images/learning-image_eylqwm.jpg @adamswonder 

https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532588/website-images/community-image_pkeqwj.jpg @JamesMGithire

NOTE: Kindly just pick one image to implement and remember to follow our contribution guidelines before you commit a pull request

For the recaptcha key use this:
`6LenksIiAAAAACrW2PQc1bWg_Kqj1HKh40q4tsjG`

### Acceptance Criteria

- [ ] The images are loading correctly.

**Comment by isaacknjama** [comment]
I'd like to add this image: https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532589/website-images/weekly_standups_lg3rth.jpg

**Comment by orama254** [comment]
Hello @isaack-mungui, feel free to contribute

**Comment by EstherWMaina** [comment]
I would like to implement this image https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532588/website-images/no-image_nnaxwk.jpg

**Comment by orama254** [comment]
Hello @EstherWMaina , feel free to contribute

**Comment by remigathoni** [comment]
I would like to add this image:  https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532589/website-images/community_sessions_xsyd8d.jpg

**Comment by adamswonder** [comment]
Picked to append this image: https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532589/website-images/community_sessions_xsyd8d.jpg

**Comment by JamesMGithire** [comment]
Picked this image: https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532588/website-images/community-image_pkeqwj.jpg

**Comment by orama254** [comment]
Hello @remigathoni, feel free to contribute

**Comment by orama254** [comment]
Hello @adamswonder, the image has been claimed by @remigathoni, please choose another one

**Comment by orama254** [comment]
Hello @JamesMGithire feel free to contribute

**Comment by adamswonder** [comment]
> Picked to append this image: https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532589/website-images/community_sessions_xsyd8d.jpg
How about: https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532588/website-images/learning-image_eylqwm.jpg

**Comment by orama254** [comment]
> > Picked to append this image: https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532589/website-images/community_sessions_xsyd8d.jpg
> > How about: https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532588/website-images/learning-image_eylqwm.jpg

@adamswonder feel free to contribute

**Comment by dmungai97** [comment]
Il do this image: 
 https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532588/website-images/mentorship-image_tz0mor.jpg

**Comment by dmungai97** [comment]
Ill do:
https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532588/website-images/mentorship-image_tz0mor.jpg

**Comment by gitahievans** [comment]
I would like to work on this image https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532588/website-images/hero-image_dqpm0k.jpg

**Comment by kabszac** [comment]
Hi can I work on this https://res.cloudinary.com/reactjs-devs-ke/image/upload/v1678532588/website-images/mentorship-image_tz0mor.jpg

**Comment by orama254** [comment]
Hello @kabszac 

The remaining images are currently under review on Pull #131 but feel free to be on the lookout for more issues on the project.
