### ISSUE TITLE
Project House Keeping-05-04-2023

### ISSUE THREAD

**Issue by orama254** [reactdeveloperske/reactdevske-website#130]
### Description

Add some changes to the project's contribution guidelines based on the new developments on the project and finish up on the remaining CDN images on issue #118 

### Solution description

Submit a pull request with changes that solve these issues.

**Comment by enowdivine** [comment]
Hello @orama254, I would like to work on this issue

**Comment by orama254** [comment]
Hello @enowdivine 

This is currently in review on pull #131 . I forgot to self assign myself this.

**Comment by orama254** [comment]
Closing as complete
