### ISSUE TITLE
Add Figma design file link to the project readme

### ISSUE THREAD

**Issue by amosmachora** [reactdeveloperske/reactdevske-website#135]
### Description

This is for new contributors to much more easily find the link. I experienced this issue myself when I had to post a question on the forums for someone to reply with the link which is a collaboration barrier that most people would rather avoid.

### Solution description

It's simple ill just add the link to the readme.

### Additional information

You can assign me

**Comment by orama254** [comment]
Hello @amosmachora 

Go ahead, remember to go through our [contribution guidelines](https://github.com/reactdeveloperske/reactdevske-website/blob/main/CONTRIBUTING.md)
