### ISSUE TITLE
Make NavBar sticky

### ISSUE THREAD

**Issue by octaviookumu** [reactdeveloperske/reactdevske-website#137]
### What feature are you adding?

making the navbar component sticky

### Describe your issue

Description
I experienced an issue where upon trying to scroll down I was unable to access the navbar.
Having it reachable when scrolling would enable ease in navigating, especially if we plan to add more pages in future.

https://github.com/reactdeveloperske/reactdevske-website/assets/48207524/8318e48e-831f-4df2-a8b1-84e5bcb9279a

Solution description
Make the navbar stick to the top when scrolling.

Additional information
Here is a short demo of what it would look like. Not the final thing however, only for demo purposes.
Among the changes I would suggest is:
- Retaining the initial clear background
- Fading into a white background and black coloured text when the user starts scrolling
- Transition back into the clear background once the user scrolls back to the the top

You can add any more recommendations you see fit.

https://github.com/reactdeveloperske/reactdevske-website/assets/48207524/f078b25c-be17-4908-b3e1-c7750362708d

**Comment by orama254** [comment]
Hello @octaviookumu,

These are good suggestions, would you like to take it up so that I can assign you the issue, or I can add the relevant tags so that someone can take it up?

**Comment by octaviookumu** [comment]
Hello @orama254 , sure I can take it up. Thanks

**Comment by orama254** [comment]
@octaviookumu 

You have been assigned, remember to go through our [contribution guidelines](https://github.com/reactdeveloperske/reactdevske-website/blob/main/CONTRIBUTING.md) and also feel free to reach out incase anything isn't clear.

Happy hacking!!!

**Comment by orama254** [comment]
Closing this as completed, thanks @octaviookumu
