### ISSUE TITLE
Add git hooks

### ISSUE THREAD

**Issue by EspiraMarvin** [reactdeveloperske/reactdevske-website#139]
### What feature are you adding?

adding git hooks with husky

### Describe your issue

We can use Husky to lint commit messages, run tests, and lint code when you commit or push code. We can specify commit message formats, add pre-commit and post-merge hooks

**Comment by orama254** [comment]
@EspiraMarvin Great feature suggestion.

Are there specific tasks on this project that you want to target with the git hooks?

**Comment by EspiraMarvin** [comment]
@orama254 There are specific tasks to handle with git hooks here:
1.  Automate code linting after staging file changes
2.  Enforcing a formal(one-way) format for writing commit messages. this formatting will be helpful to track meaningful changes/releases of the app via the CHANGELOG, 
Of course, other use cases exist, but the above two can be applied to this project.

**Comment by orama254** [comment]
@EspiraMarvin 

Could you create one that runs the validate script? This has all the necessary steps e.g linting, testing and typechecking.

If yes then I can give you a go ahead and assign you this issue

**Comment by EspiraMarvin** [comment]
@orama254 yes, that's possible, you can assign me the issue

**Comment by SnowJunior** [comment]
@orama254 is this still open ?

I would like to handle it

**Comment by orama254** [comment]
> @orama254 is this still open ?
> 
> I would like to handle it

hey @SnowJunior it's been sorted on pull #141

**Comment by orama254** [comment]
Closing as complete.
