### ISSUE TITLE
An About page for the community website

### ISSUE THREAD

**Issue by nassersaazi** [reactdeveloperske/reactdevske-website#15]
**Problem description**
I'm kind of lost when I open the website and can't get a general overview on this beautiful react community

**Solution description**
I suggest creating a well-designed nav menu with a link to an About page that describes what the community is about . Perhaps more relevant links can be added to the nav menu as we go along.

**Comment by orama254** [comment]
Greetings, @nassersaazi ,

Everything is currently an ongoing process as at now, we are setting everything up as we speak and this will be considered and is on the development pipeline as we progress

Be on the lookout for when these changes take effect or when an issue is posted for consideration

**Comment by nassersaazi** [comment]
thanks for the feedback @orama254 . is it okay if i make a pull request for the issue? i have some ideas in mind.

**Comment by orama254** [comment]
@nassersaazi You can checkout the design discussion and make suggestions there

**Comment by nassersaazi** [comment]
any links to the design discussion?

**Comment by orama254** [comment]
@nassersaazi you can find the various discussions [here](https://github.com/reactdeveloperske/reactdevske-website/discussions)

**Comment by orama254** [comment]
Closing due to staleness and new project structure
