### ISSUE TITLE
Include contact/social media links in project README

### ISSUE THREAD

**Issue by nassersaazi** [reactdeveloperske/reactdevske-website#16]
Wouldn't it be nice if someone could as well access community social media channels(discord, telegram etc...)? from the project README file

**Comment by orama254** [comment]
Cool suggestion,

can you make a pull request with these suggestions for consideration?

**Comment by nassersaazi** [comment]
alright. will do that. thanks!

**Comment by orama254** [comment]
Resolved with #17 pull request
