### ISSUE TITLE
Convert current codebase to Next.js

### ISSUE THREAD

**Issue by orama254** [reactdeveloperske/reactdevske-website#30]
### What feature are you adding?

Convert Codebase to Next.Js

### Describe your issue

The current codebase is written in CRA(Create-react-app) and we want you to convert it to Create Next App

Checkout the nextjs Documentation [HERE](https://nextjs.org/docs) for more information on this

**Comment by Esther-Wavinya** [comment]
Can I work on this?

**Comment by bmwasonga** [comment]
you can

**Comment by orama254** [comment]
Hi @Esther-Wavinya,

We have taken up this issue internally because of some config issues that are arising, but feel free to claim another issue in the issues section [HERE](https://github.com/reactdeveloperske/reactdevske-website/issues).

**Comment by Esther-Wavinya** [comment]
Okay fine
