### ISSUE TITLE
Install and configure Tailwind CSS

### ISSUE THREAD

**Issue by stephanieopala** [reactdeveloperske/reactdevske-website#31]
### What feature are you adding?

Install and configure Tailwind CSS

### Description

Install and configure Tailwind CSS. 
[Here](https://tailwindcss.com/docs/guides/nextjs) is a link to the documentation with a guide on setting up Tailwind in a Next JS application.

**Comment by weshy007** [comment]
May I work on this issue?

**Comment by stephanieopala** [comment]
Hi, @weshy007 one of the project maintainers is working on this since it's a high priority at the moment.
We'll have other issues that you can work on.

**Comment by weshy007** [comment]
Cool 👍
