### ISSUE TITLE
Create the navigation bar

### ISSUE THREAD

**Issue by stephanieopala** [reactdeveloperske/reactdevske-website#32]
### What feature are you adding?

Creating the navigation bar

### Description

 Create a navigation bar with the following navigation links as per the design.

- About us
- Members
- Events
- News
- Forum
- Contact
- Join Community

### Design link
[Design](https://www.figma.com/file/ERYYmMHJBj06mlUft0Qa3q/open-design)

![Navigation](https://user-images.githubusercontent.com/70809537/173360421-94caca72-2958-4781-8f3b-642d9b6e1688.PNG)

**Comment by cwnuramirah** [comment]
Hi, can I work on this?

**Comment by zidanegimiga** [comment]
No, it's fine I'll just proceed working on the landing page.

**Comment by stephanieopala** [comment]
Tailwind CSS @zidanegimiga

**Comment by orama254** [comment]
I think this issue has been sorted for now.

closing it as resolved...
