### ISSUE TITLE
Create the landing page

### ISSUE THREAD

**Issue by stephanieopala** [reactdeveloperske/reactdevske-website#33]
### What feature are you adding?

Creating the landing page

### Description

Create the landing page section. This includes the title and the three card components.

### Design Link
[Design](https://www.figma.com/file/ERYYmMHJBj06mlUft0Qa3q/open-design)

![Landing-Page](https://user-images.githubusercontent.com/70809537/173360024-0154ebc5-3165-46bb-8d35-d6576acc50df.PNG)

**Comment by zidanegimiga** [comment]
May I take this one?

**Comment by stephanieopala** [comment]
@zidanegimiga I have assigned this issue to you. Just to note, there is an update to the repository that the maintainers are working on. Therefore, kindly wait for the repo to be updated, before you start working on this. 
The change will be pushed in the next hour or so.

**Comment by orama254** [comment]
sure @zidanegimiga , it's all systems go now
