### ISSUE TITLE
Create the About Us section 

### ISSUE THREAD

**Issue by stephanieopala** [reactdeveloperske/reactdevske-website#34]
### What feature are you adding?

Creating the About Us section

### Description

Create About Us section.

### Design link
[Design](https://www.figma.com/file/ERYYmMHJBj06mlUft0Qa3q/open-design)

**Comment by enowdivine** [comment]
Hello, I'd like to contribute to this issue

**Comment by stephanieopala** [comment]
@enowdivine I have assigned this issue to you. Just a note before you start working on it, we are migrating the repo to Next JS, therefore kindly wait for it to be updated before you pull. Thanks

**Comment by enowdivine** [comment]
Ok great, no problem

**Comment by stephanieopala** [comment]
@enowdivine Hello, don't forget to update your fork. There are some changes that have been pushed to this repo

**Comment by enowdivine** [comment]
sure thing. I'll do that immediately
