### ISSUE TITLE
Add fonts to the project

### ISSUE THREAD

**Issue by bmwasonga** [reactdeveloperske/reactdevske-website#42]
### What feature are you adding?

Fonts and Typography

### Describe your issue

We need to add the fonts to the page as they have been described in the design file. 
You will need to add the fonts, we recommend [google fonts](https://fonts.google.com/).  

refer to the design [ here](https://www.figma.com/file/ERYYmMHJBj06mlUft0Qa3q/open-design?node-id=0%3A1)

**Comment by zidanegimiga** [comment]
Added fonts on my fork can I close this issue with it?

**Comment by stephanieopala** [comment]
Hello @zidanegimiga We will close this issue once your PR with said changes in the font is reviewed, and adheres to the requirements.

**Comment by orama254** [comment]
I think this issue has been sorted out now

closing it as solved
