### ISSUE TITLE
Create event page component 

### ISSUE THREAD

**Issue by bmwasonga** [reactdeveloperske/reactdevske-website#43]
### What feature are you adding?

Event page component 

### Describe your issue

Create a reusable component that will be used to show different events that the community will showcase. 
![Screenshot from 2022-06-14 12-01-48](https://user-images.githubusercontent.com/65865227/173538839-66c93c7b-f69b-4e13-83d8-6ef3a4c2122b.png)

The component should appear like the screenshot above and be able to be re-sized depending on the use i.e either mobile, tablet or desktop.

**Comment by AJ-Kulundu** [comment]
@bmwasonga I want to take the task of creating the reusable component for the events page and landing page
