### ISSUE TITLE
Create an "🚧Under Construction🚧" Banner at the Top of the page

### ISSUE THREAD

**Issue by orama254** [reactdeveloperske/reactdevske-website#51]
### What feature are you adding?

Adding an Under Construction Banner at the top of the page

### Describe your issue

When coming to the page for the first time in its current form, you will be met by a super basic page. Wanted a way to show new visitors that the page is currently under construction with a construction banner component at the top of the page.

##### example image

![under-construction-banner](https://user-images.githubusercontent.com/50571688/173837562-87770aef-787f-4f15-9af0-01764dccf242.png)

Here is also a nice article from css-tricks incase you want to take up the issue
[CSS-TRICKS ARTICLE](https://css-tricks.com/stripes-css/) on the diagonal colored stripes category.

**Comment by king-kanda** [comment]
must the page have stripes or a neat design that indicates that the page is under construction will do?

i may have a few ideas in mind

**Comment by orama254** [comment]
Hello @king-kanda 

thanks for the pull requests so far.

It's advisable in accordance to our [contributor guidelines](https://github.com/reactdeveloperske/reactdevske-website/blob/main/CONTRIBUTING.md) that you are assigned a task first before working on a feature.

from this thread it's @bilalscripts that made the first claim so I'll have to consider their claim first as it is first come first serve.

**Comment by orama254** [comment]
Hello @bilalscripts,

are you ok working on this issue...we just want a banner at the top to indicate that the website is currently under construction.

ideally it should also be responsive.

**Comment by bilalscripts** [comment]
hey, @orama254 yep I'm available and ok with working on this issue, assign me this task thanks..
