### ISSUE TITLE
Add pages

### ISSUE THREAD

**Issue by stephanieopala** [reactdeveloperske/reactdevske-website#52]
### What feature are you adding?

Add pages/routes

### Description

Add the following pages/routes in the pages folder.
Members
Events
News
Forum
Contact

**Comment by Lekipising** [comment]
Hey, would like to take this up.

**Comment by Lekipising** [comment]
I would like to work on the following related items for the project:

1. Convert all pages and components to use `jsx` instead of `js`
2. Create a common routes constant file to store all routes paths. To ensure consistency.

Let me know if I can add that in @stephanieopala

**Comment by stephanieopala** [comment]
@Lekipising Yes, go ahead
