### ISSUE TITLE
Correct command mistakes in CONTRIBUTING.md and improve how to contribute

### ISSUE THREAD

**Issue by dmuyah** [reactdeveloperske/reactdevske-website#57]
### Description

Its minor but can be confusing to someone getting started 
on CONTRIBUTING.md the commands are  
`yarn`
instead of 
`yarn install`

on running app in development mode:
its 
`yarn start` 
instead of
`yarn run dev `
or
`npm run dev`

### Screenshots

![Screenshot from 2022-06-16 23-18-03](https://user-images.githubusercontent.com/107351277/174157309-3b8ac77d-e91e-40ab-8850-59c864ff6671.png)

### Additional information

suggested:

improve the how to contribute to be beginner friendly

**Comment by kihuni** [comment]
Is this issue still available? I would like to work on it

**Comment by orama254** [comment]
> Is this issue still available? I would like to work on it

Hello @kihuni, this issue is currently being worked on by @dmuyah 

feel free to checkout the issues tab for more upcoming issues

**Comment by kihuni** [comment]
Thank you @orama254 I will stay tuned.
