### ISSUE TITLE
Implement the About section

### ISSUE THREAD

**Issue by orama254** [reactdeveloperske/reactdevske-website#78]
### What feature are you adding?

About Section

### Requirements

- Create a component named `AboutUs` in the `components` folder that implements the screenshots below.
- It should render a `section` tag with an `id` of `about-us`.
- Include the component in `index.page.tsx`

**SCREENSHOT**

**Desktop**
![about-section-screenshot](https://user-images.githubusercontent.com/50571688/194319021-149bb622-9000-4177-98b9-cef15eb28bd1.png)

**Mobile**

![about-section-mobile](https://user-images.githubusercontent.com/50571688/194678517-02a0ba0f-4971-40be-9489-c8b99e0a9260.png)

[Figma Design](https://www.figma.com/file/TVwnaDhBGeVdnVKdf6H91C/React-developers-community-website?node-id=741%3A976)

### Acceptance Criteria

- [ ] The implementation should match the design - text content, typography, capitalization and spacing.
- [ ] The UI should be responsive and work well on both desktop and mobile viewports.

**Comment by Prerna-Bhargava** [comment]
Hi @orama254 , please assign this to me.

**Comment by orama254** [comment]
Hey @Prerna-Bhargava,

Go ahead, remember to go through our [contribution guidelines](https://github.com/reactdeveloperske/reactdevske-website/blob/main/CONTRIBUTING.md) and also evaluate the acceptance criteria before submitting a pull request.

Happy hacking!!!

**Comment by AJ-Kulundu** [comment]
@orama254 has the issue been resolved? I would like to be assigned to it.

**Comment by Prerna-Bhargava** [comment]
Hey @orama254 so sorry as I couldn't continue with this issue. I think you can assign @AJ-Kulundu this issue.
