### ISSUE TITLE
Implement the Contact Us Section (Form UI)

### ISSUE THREAD

**Issue by orama254** [reactdeveloperske/reactdevske-website#82]
### Depends on

- Button Component #85 

### What feature are you adding?

Contact Us Section (Form UI)

### Requirements

- Create a component named `ContactUs` in the `components` folder that implements the screenshots below.
- It should render a `section` tag with an `id` of `contact-us`.
- Include the component in `index.page.tsx`
- The form should not have any logic, this ticket is only concerned with the presentation.
- Reuse the `Button` component.
- The form should be accessible with proper labels linked to the inputs.
- Both the name, email and message fields should have the `required` attribute.

**SCREENSHOT**

**Desktop**
![contact-section](https://user-images.githubusercontent.com/50571688/194323291-a003dc89-f12c-4731-a721-e21e4edfaf9f.png)

**Mobile**
![contact-section-mobile](https://user-images.githubusercontent.com/50571688/194678887-fed0fabc-ef46-4c1d-8dfd-4633d8e25dab.png)

[Figma Design](https://www.figma.com/file/TVwnaDhBGeVdnVKdf6H91C/React-developers-community-website?node-id=32%3A6)

### Acceptance Criteria

- [ ] The implementation should match the design - text content, typography, capitalization and spacing.
- [ ] The UI should be responsive and work well on both desktop and mobile viewports.
- [ ] Both the name, email and message fields have the `required` attribute.
- [ ] Inputs have accessible labels.

**Comment by devKiratu** [comment]
Hey @orama254 please assign me this issue

**Comment by devKiratu** [comment]
> Hey @devKiratu 
> 
> Go ahead, remember to go through our [contribution guidelines](https://github.com/reactdeveloperske/reactdevske-website/blob/main/CONTRIBUTING.md) and also evaluate the acceptance criteria before submitting a pull request.
> 
> Happy hacking!!!

Thank you!
