### ISSUE TITLE
Implement the Button Component

### ISSUE THREAD

**Issue by orama254** [reactdeveloperske/reactdevske-website#85]
### What feature are you adding?

Button Component

### Requirements

- Button
	- Create a component named `Button` in the `components` folder that implements the screenshots below.
	- It should use the native HTML `button` element.
	- It should accept all HTML `button` props.
- Link
	- Create a component named `LinkButton` in the `components` folder that implements the screenshots below.
	- It should use the native HTML `a` element.
	- It should accept all HTML `a` props.
- Both buttons should handle long labels by hiding the overflow with an ellipsis.
- Both buttons should match the design.

**SCREENSHOTS**

[Figma Design](https://www.figma.com/file/TVwnaDhBGeVdnVKdf6H91C/React-developers-community-website?node-id=741%3A976)

### Acceptance Criteria

- [ ] The implementation should match the design - typography and spacing.
- [ ] The buttons should be responsive and work well on both desktop and mobile viewports.
- [ ] Long labels should be handled correctly.

**Comment by enowdivine** [comment]
Hi @orama254 Please assign the button component to me.

**Comment by orama254** [comment]
Hey @enowdivine 

Go ahead, remember to go through our [contribution guidelines](https://github.com/reactdeveloperske/reactdevske-website/blob/main/CONTRIBUTING.md) and also evaluate the acceptance criteria before submitting a pull request.

Happy hacking!!!

**Comment by orama254** [comment]
@enowdivine 

**ALSO NOTE:** This issue has some other dependencies, eg https://github.com/reactdeveloperske/reactdevske-website/issues/77 & https://github.com/reactdeveloperske/reactdevske-website/issues/82 How soon do you think you can submit a PR?

**Comment by enowdivine** [comment]
> @enowdivine
> 
> **ALSO NOTE:** This issue has some other dependencies, eg #77 & #82 How soon do you think you can submit a PR?

ok noted. I can submit a PR in a day maximum.

**Comment by enowdivine** [comment]
Hello @orama254 the figma design link leads to no where. Please can you check that

**Comment by orama254** [comment]
My bad @enowdivine 

It should be all good now, nice catch.

Let me know if there is anything else you would want assistance with.

**Comment by enowdivine** [comment]
Ok sure.
