### ISSUE TITLE
Failing tests in webkit browser

### ISSUE THREAD

**Issue by nyandika** [reactdeveloperske/reactdevske-website#97]
### Description

This is in relation to [this failing action](https://github.com/reactdeveloperske/reactdevske-website/actions/runs/3275876580/jobs/5391260078) caused by #93 from @EspiraMarvin

Going through the logs this is not caused as a result of webkit timeout due to waiting for scrolling event, the scrolling event succeeds. what is timing out is the locator.click event

Digging into it and running the tests locally in debug mode I found out the discrepancy. 
This part of the log: `selector resolved to hidden <a target="_blank" href="[https://kommunity.com/reac…](https://kommunity.com/reac%E2%80%A6)>See More</a>` 

Not sure why webkit is marking it as hidden. This doesn't happen on local either so hard to catch it
Playwright will throw a TimeoutError when element is not visible. More [here](https://playwright.dev/docs/actionability)

**Comment by antosan** [comment]
Interestingly, the test went through when I merged the PR ([run](https://github.com/reactdeveloperske/reactdevske-website/actions/runs/3275663992/jobs/5390834844)) even though Marvin had raised the fact that it [didn't work on safari](https://github.com/reactdeveloperske/reactdevske-website/pull/93#discussion_r998529312).

I opened a PR where I made an adjustment to get the page from the context. That alone did not fix it though. I ended up updating playwright and giving the test a larger timeout on webkit to prevent it from timing out. 

Node.js 12 actions are deprecated, I updated `actions/checkout`, `actions/setup-node`,` actions/upload-artifact` to `v3`.

@nyandika Kindly have a look at the PR.
